apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotels
  labels:
    apps: hotels
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotels
      tier: monolith
  template:
    metadata:
      labels:
        app: hotels
        tier: monolith
    spec:
      containers:
      - name: hotels
        image: ghcr.io/go-elevate/k8s4arch-hotels:monolith
        ports:
        - containerPort: 80
