apiVersion: v1
kind: PersistentVolume
metadata:
  name: hotels-db
spec:
  storageClassName: hotels-db
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/hotels-db"

