apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hotels-db
  namespace: hotels
spec:
  storageClassName: hotels-db
  volumeName: hotels-db
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
